import { NextRequest, NextResponse } from "next/server";
import { YoutubeTranscript } from "youtube-transcript";
import type { TranscriptResult, TranscriptLine } from "@/types/clip";

export const preferredRegion = "sin1";
export const dynamic = "force-dynamic";

function extractVideoId(url: string): string | null {
  try {
    const parsed = new URL(url);

    // youtu.be short links
    if (parsed.hostname === "youtu.be") {
      return parsed.pathname.slice(1) || null;
    }

    // youtube.com/watch?v=...
    if (parsed.hostname.includes("youtube.com")) {
      const v = parsed.searchParams.get("v");
      if (v) return v;

      // /shorts/VIDEO_ID or /live/VIDEO_ID
      const match = parsed.pathname.match(/^\/(shorts|live)\/([a-zA-Z0-9_-]+)/);
      if (match) return match[2];
    }

    return null;
  } catch {
    // Maybe the user pasted just the video ID
    if (/^[a-zA-Z0-9_-]{11}$/.test(url)) return url;
    return null;
  }
}

interface PipedSubtitle {
  url: string;
  name: string;
  code: string;
  autoGenerated?: boolean;
}

interface PipedStreamResponse {
  subtitles?: PipedSubtitle[];
}

function parseVTT(vttText: string): TranscriptLine[] {
  const lines = vttText.split("\n");
  const result: TranscriptLine[] = [];
  const timestampRe = /([0-9:.]+)\s-->\s([0-9:.]+)/;

  function parseTime(timeStr: string): number {
    const parts = timeStr.trim().split(':');
    let secs = 0;
    if (parts.length === 3) {
      // HH:MM:SS.mmm
      secs = parseInt(parts[0]) * 3600 + parseInt(parts[1]) * 60 + parseFloat(parts[2]);
    } else if (parts.length === 2) {
      // MM:SS.mmm
      secs = parseInt(parts[0]) * 60 + parseFloat(parts[1]);
    }
    return secs;
  }

  for (let i = 0; i < lines.length; i++) {
    const match = timestampRe.exec(lines[i]);
    if (!match) continue;

    const startSecs = parseTime(match[1]);
    const endSecs = parseTime(match[2]);

    const textParts: string[] = [];
    let j = i + 1;
    // Baca baris teks sampai ketemu baris kosong atau panah waktu berikutnya
    while (j < lines.length && lines[j].trim() !== "" && !lines[j].includes("-->")) {
      const cleaned = lines[j].replace(/<[^>]+>/g, "").trim();
      if (cleaned) textParts.push(cleaned);
      j++;
    }

    if (textParts.length > 0) {
      result.push({
        text: textParts.join(" "),
        offset: startSecs,
        duration: endSecs - startSecs,
      });
    }
  }

  return result;
}

const PIPED_INSTANCES = [
  "https://pipedapi.smnz.de",
  "https://api.piped.projectsegfau.lt",
  "https://piped-api.lunar.icu",
];

async function fetchFromPiped(videoId: string): Promise<TranscriptLine[]> {
  let data: PipedStreamResponse | null = null;
  let lastError: string = "";

  for (const instance of PIPED_INSTANCES) {
    try {
      const pipedRes = await fetch(
        `${instance}/streams/${videoId}`
      );
      if (!pipedRes.ok) {
        lastError = `${instance} → ${pipedRes.status}`;
        continue;
      }
      data = await pipedRes.json();
      if (data?.subtitles && data.subtitles.length > 0) break;
      lastError = `${instance} → tidak ada subtitle`;
    } catch (e) {
      lastError = `${instance} → ${e instanceof Error ? e.message : "fetch gagal"}`;
      continue;
    }
  }

  if (!data?.subtitles || data.subtitles.length === 0) {
    throw new Error(`Semua instance Piped gagal. Terakhir: ${lastError}`);
  }

  // Prioritas: Indonesia > Inggris > auto-generated > subtitle pertama
  let sub = data.subtitles.find(
    (s) => s.code.startsWith("id") && !s.autoGenerated
  );
  if (!sub) {
    sub = data.subtitles.find(
      (s) => s.code.startsWith("en") && !s.autoGenerated
    );
  }
  if (!sub) {
    sub = data.subtitles.find((s) => s.code.startsWith("id"));
  }
  if (!sub) {
    sub = data.subtitles.find((s) => s.code.startsWith("en"));
  }
  if (!sub) {
    sub = data.subtitles[0];
  }

  const vttRes = await fetch(sub.url);
  if (!vttRes.ok) {
    throw new Error(`Gagal mengambil file VTT: ${vttRes.status}`);
  }

  const vttText = await vttRes.text();
  const parsed = parseVTT(vttText);

  if (parsed.length === 0) {
    throw new Error("Parsing VTT gagal, tidak ada baris yang terbaca");
  }

  return parsed;
}

async function fetchFromInvidious(videoId: string): Promise<TranscriptLine[]> {
  const instances = [
    "https://inv.tux.pizza",
    "https://invidious.weblibre.org",
    "https://invidious.flokinet.to",
    "https://invidious.perennialte.ch",
  ];

  let lastError = "";
  for (const baseUrl of instances) {
    try {
      const res = await fetch(`${baseUrl}/api/v1/videos/${videoId}`);
      if (!res.ok) continue;

      const data = await res.json();
      if (!data.captions || data.captions.length === 0) continue;

      // Prioritas: Indonesia -> Inggris -> Pertama (Support Auto-generated)
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      let sub = data.captions.find((c: any) => c.languageCode === "id" || c.label?.includes("Indonesian"));
      if (!sub) sub = data.captions.find((c: any) => c.languageCode === "en" || c.label?.includes("English"));
      if (!sub) sub = data.captions[0];

      const vttUrl = sub.url.startsWith("http") ? sub.url : `${baseUrl}${sub.url}`;
      const vttRes = await fetch(vttUrl);
      if (!vttRes.ok) continue;

      const vttText = await vttRes.text();
      const parsed = parseVTT(vttText);
      if (parsed.length > 0) return parsed;
    } catch (err: unknown) {
      lastError = err instanceof Error ? err.message : "fetch gagal";
      continue;
    }
  }
  throw new Error(`Semua instance Invidious gagal. Error: ${lastError}`);
}

export async function POST(request: NextRequest) {
  const body = await request.json();
  const url: string = body.url;

  if (!url || typeof url !== "string") {
    return NextResponse.json<TranscriptResult>(
      { success: false, error: "URL YouTube diperlukan" },
      { status: 400 }
    );
  }

  const videoId = extractVideoId(url);

  if (!videoId) {
    return NextResponse.json<TranscriptResult>(
      { success: false, error: "Format URL YouTube tidak valid" },
      { status: 400 }
    );
  }

  let transcript: TranscriptLine[];

  try {
    // Lapis 1: Coba module bawaan
    transcript = await YoutubeTranscript.fetchTranscript(videoId);
    if (!transcript || transcript.length === 0) throw new Error("Transcript kosong");
  } catch (primaryErr: unknown) {
    try {
      // Lapis 2: Invidious API (Support Auto-Generated)
      transcript = await fetchFromInvidious(videoId);
    } catch (invErr: unknown) {
      try {
        // Lapis 3: Piped API (Hanya manual subs)
        transcript = await fetchFromPiped(videoId);
      } catch (pipedErr: unknown) {
        const msg1 = primaryErr instanceof Error ? primaryErr.message : "Gagal YT";
        const msg2 = invErr instanceof Error ? invErr.message : "Gagal Invidious";
        return NextResponse.json<TranscriptResult>(
          { success: false, error: `Utama: ${msg1} | Invidious: ${msg2}` },
          { status: 400 }
        );
      }
    }
  }

  return NextResponse.json<TranscriptResult>({
    success: true,
    videoId,
    transcript,
  });
}
