import { NextRequest, NextResponse } from "next/server";
import { YoutubeTranscript } from "youtube-transcript";
import type { TranscriptResult, TranscriptLine } from "@/types/clip";

export const preferredRegion = "sin1";
export const dynamic = "force-dynamic";

function extractVideoId(url: string): string | null {
  try {
    const parsed = new URL(url);

    // youtu.be short links
    if (parsed.hostname === "youtu.be") {
      return parsed.pathname.slice(1) || null;
    }

    // youtube.com/watch?v=...
    if (parsed.hostname.includes("youtube.com")) {
      const v = parsed.searchParams.get("v");
      if (v) return v;

      // /shorts/VIDEO_ID or /live/VIDEO_ID
      const match = parsed.pathname.match(/^\/(shorts|live)\/([a-zA-Z0-9_-]+)/);
      if (match) return match[2];
    }

    return null;
  } catch {
    // Maybe the user pasted just the video ID
    if (/^[a-zA-Z0-9_-]{11}$/.test(url)) return url;
    return null;
  }
}

interface PipedSubtitle {
  url: string;
  name: string;
  code: string;
  autoGenerated?: boolean;
}

interface PipedStreamResponse {
  subtitles?: PipedSubtitle[];
}

function parseVTT(vttText: string): TranscriptLine[] {
  const lines = vttText.split("\n");
  const result: TranscriptLine[] = [];
  const timestampRe = /(\d+):(\d{2}):(\d{2})[.](\d{3})\s-->\s(\d+):(\d{2}):(\d{2})[.](\d{3})/;

  for (let i = 0; i < lines.length; i++) {
    const match = timestampRe.exec(lines[i]);
    if (!match) continue;

    const startMs =
      parseInt(match[1]) * 3600000 +
      parseInt(match[2]) * 60000 +
      parseInt(match[3]) * 1000 +
      parseInt(match[4]);
    const endMs =
      parseInt(match[5]) * 3600000 +
      parseInt(match[6]) * 60000 +
      parseInt(match[7]) * 1000 +
      parseInt(match[8]);

    // Collect text lines until next blank line
    const textParts: string[] = [];
    let j = i + 1;
    while (j < lines.length && lines[j].trim() !== "") {
      // Skip position/alignment tags like <00:00:01.000>
      const cleaned = lines[j].replace(/<[^>]+>/g, "").trim();
      if (cleaned) textParts.push(cleaned);
      j++;
    }

    if (textParts.length > 0) {
      result.push({
        text: textParts.join(" "),
        offset: startMs / 1000,
        duration: (endMs - startMs) / 1000,
      });
    }
  }

  return result;
}

const PIPED_INSTANCES = [
  "https://pipedapi.smnz.de",
  "https://api.piped.projectsegfau.lt",
  "https://piped-api.lunar.icu",
];

async function fetchFromPiped(videoId: string): Promise<TranscriptLine[]> {
  let data: PipedStreamResponse | null = null;
  let lastError: string = "";

  for (const instance of PIPED_INSTANCES) {
    try {
      const pipedRes = await fetch(
        `${instance}/streams/${videoId}`
      );
      if (!pipedRes.ok) {
        lastError = `${instance} → ${pipedRes.status}`;
        continue;
      }
      data = await pipedRes.json();
      if (data?.subtitles && data.subtitles.length > 0) break;
      lastError = `${instance} → tidak ada subtitle`;
    } catch (e) {
      lastError = `${instance} → ${e instanceof Error ? e.message : "fetch gagal"}`;
      continue;
    }
  }

  if (!data?.subtitles || data.subtitles.length === 0) {
    throw new Error(`Semua instance Piped gagal. Terakhir: ${lastError}`);
  }

  // Prioritas: Indonesia > Inggris > auto-generated > subtitle pertama
  let sub = data.subtitles.find(
    (s) => s.code.startsWith("id") && !s.autoGenerated
  );
  if (!sub) {
    sub = data.subtitles.find(
      (s) => s.code.startsWith("en") && !s.autoGenerated
    );
  }
  if (!sub) {
    sub = data.subtitles.find((s) => s.code.startsWith("id"));
  }
  if (!sub) {
    sub = data.subtitles.find((s) => s.code.startsWith("en"));
  }
  if (!sub) {
    sub = data.subtitles[0];
  }

  const vttRes = await fetch(sub.url);
  if (!vttRes.ok) {
    throw new Error(`Gagal mengambil file VTT: ${vttRes.status}`);
  }

  const vttText = await vttRes.text();
  const parsed = parseVTT(vttText);

  if (parsed.length === 0) {
    throw new Error("Parsing VTT gagal, tidak ada baris yang terbaca");
  }

  return parsed;
}

export async function POST(request: NextRequest) {
  const body = await request.json();
  const url: string = body.url;

  if (!url || typeof url !== "string") {
    return NextResponse.json<TranscriptResult>(
      { success: false, error: "URL YouTube diperlukan" },
      { status: 400 }
    );
  }

  const videoId = extractVideoId(url);

  if (!videoId) {
    return NextResponse.json<TranscriptResult>(
      { success: false, error: "Format URL YouTube tidak valid" },
      { status: 400 }
    );
  }

  let transcript: TranscriptLine[];

  try {
    transcript = await YoutubeTranscript.fetchTranscript(videoId);

    if (!transcript || transcript.length === 0) {
      throw new Error("Transcript kosong dari youtube-transcript");
    }
  } catch (primaryErr: unknown) {
    // youtube-transcript gagal (IP block, dll) — coba Piped API sebagai fallback
    try {
      transcript = await fetchFromPiped(videoId);
    } catch (fallbackErr: unknown) {
      const primaryMsg = primaryErr instanceof Error ? primaryErr.message : "Gagal youtube-transcript";
      const fallbackMsg = fallbackErr instanceof Error ? fallbackErr.message : "Gagal Piped API";

      return NextResponse.json<TranscriptResult>(
        { success: false, error: `Utama: ${primaryMsg} | Fallback: ${fallbackMsg}` },
        { status: 400 }
      );
    }
  }

  return NextResponse.json<TranscriptResult>({
    success: true,
    videoId,
    transcript,
  });
}
