jobs:
  cut_video_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install FFmpeg and yt-dlp
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg nodejs
          python -m pip install --upgrade pip
          pip install -U --pre "yt-dlp[default,curl-cffi]"

      - name: Download and Cut Video
        run: |
          START_TIME="${{ github.event.client_payload.start_time }}"
          END_TIME="${{ github.event.client_payload.end_time }}"
          VIDEO_URL="${{ github.event.client_payload.video_url }}"
          
          # 1. Mengambil SATU proxy acak dari file proxies.txt milikmu
          PROXY_RAW=$(shuf -n 1 proxies.txt)
          
          # 2. Membedah format Webshare (IP:PORT:USER:PASS)
          IP=$(echo "$PROXY_RAW" | cut -d':' -f1)
          PORT=$(echo "$PROXY_RAW" | cut -d':' -f2)
          USER=$(echo "$PROXY_RAW" | cut -d':' -f3)
          PASS=$(echo "$PROXY_RAW" | cut -d':' -f4)
          PROXY_URL="http://$USER:$PASS@$IP:$PORT"
          
          echo "Cutting video from $START_TIME to $END_TIME..."
          echo "Merutekan yt-dlp melalui Webshare Proxy untuk menyembunyikan IP GitHub..."
          
          # 3. Eksekusi menggunakan Proxy dan klien iOS (Tanpa Cookie!)
          yt-dlp --proxy "$PROXY_URL" \
                 --extractor-args "youtube:player_client=ios,android" \
                 --format "bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best" \
                 --download-sections "*$START_TIME-$END_TIME" \
                 --force-keyframes-at-cuts \
                 -o "clip_result.mp4" \
                 "$VIDEO_URL"

      - name: Upload Clipped Video as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: clipped-video
          path: clip_result.mp4