name: Test Repository Dispatch

on:
  repository_dispatch:
    types: [test_dispatch]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Echo payload
        run: echo "Event received! Payload=${{ toJson(github.event.client_payload) }}"
